### ISSUE TITLE
Personnalisation du champ VIDEO_FORM_FIELDS

### ISSUE THREAD

**Issue by gbarre** [EsupPortail/podv2#117]
Bonjour,

Dans la doc de configuration il est précisé que l'on peut personnaliser le champ `VIDEO_FORM_FIELDS`. La seule valeur proposée est `__all__`.
Serait-il possible d'apporter un autre exemple ou des précisions svp ?

**Comment by ptitloup** [comment]
Bonjour,
Cette variable permet de lister les champs du formulaire de gestion des vidéos. par défaut, cette variable vaut __all__ qui permet d'avoir tous les champs. Les champs sont ensuite gérer dans l'initialisation du formulaire. Vous pouvez changer cette valeur en listant entre crochet [] les champs que vous souhaitez. (Attention, certains champs sont obligatoires).
Bien cordialement
Nicolas CAN
