### ISSUE TITLE
Rechargement de page lors d'un chapitrage

### ISSUE THREAD

**Issue by sebipehemski** [EsupPortail/podv2#121]
Bonjour Nicolas,

lors d'un chapitrage d'une vidéo, nous avons détecté une chose plus ennuyante que bloquante. En effet, après avoir sauvegardé un chapitre, la page se réactualise obligeant à retrouver le moment de la fin du chapitre pour en créer un autre.

Ce n'est pas important pour des petites vidéos, mais pour des vidéos de colloque de plusieurs heures, c'est plus problématique.

En te remerciant d'avance pour l'étude de cette contribution.

Sébastien, de l'écho des Gnous.

**Comment by ptitloup** [comment]
Bonjour Sébastien, malheureusement nous manquons de développeur e nce moment pour pouvoir répondre à toutes les demandes d'amélioration. Si toi ou une connaissance à toi voulait s'y pencher, je serais ravi de l'y aider. A très bientôt, Nicolas

**Comment by ptitloup** [comment]
#131
