### ISSUE TITLE
Join PeerTube federation

### ISSUE THREAD

**Issue by tclavier** [EsupPortail/podv2#194]
As a mastodon user I want to follow my favorites courses on https://pod.univ-lille.fr. 
To do that, could you implement ActivityPub ?

**Comment by ptitloup** [comment]
Hello, why not, could you or would you help us ?

**Comment by tclavier** [comment]
I couldn't help, I really like Python but I haven't any time :-(

**Comment by ptitloup** [comment]
:'( 
We will try to add it in the roadmap ! Regards
